version: '3.5'

services:
  server:
    image: neosy/elengrab
    ports:
      - 8080:8080
    volumes:
      - downloads:/app_n/downloads
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: "1G"
          cpus: "2.0"

volumes:
  downloads:
