package helper

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestParseCookiesFile(t *testing.T) {
	content := `# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.instagram.com	TRUE	/	TRUE	1817633333	datr	_2dHapp0rKc_Bk_111Kry333
.instagram.com	TRUE	/	TRUE	1814644444	ig_did	436AFE55-D99B-44BF-8333-B960B5C3333A7
.instagram.com	TRUE	/	TRUE	1817621111	mid	akdn_w5555AG1No1-woDIz23338G_
`

	path := filepath.Join(t.TempDir(), "cookies.txt")

	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	got, err := ParseCookiesFile(path)
	if err != nil {
		t.Fatalf("ParseCookiesFile() error = %v", err)
	}

	want := []string{
		"datr=_2dHapp0rKc_Bk_111Kry333",
		"ig_did=436AFE55-D99B-44BF-8333-B960B5C3333A7",
		"mid=akdn_w5555AG1No1-woDIz23338G_",
	}

	if !reflect.DeepEqual(got, want) {
		t.Errorf("ParseCookiesFile() = %v, want %v", got, want)
	}
}
